# Laboratorium 3

In [103]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from IPython.display import Image
from IPython.core.display import HTML 
import seaborn as sns

## Wcześniej przeprowadzony preprocessing

In [17]:
### wgrywam wyczyszczony zbior danych - REGRESJA
from sklearn.datasets import load_diabetes

diabetes_X, diabetes_y = load_diabetes(return_X_y = True, as_frame=True)

In [18]:
diabetes_X

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017282 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081414  0.083740  0.027809  0.173816   

           s4        s5        s6  
0   -0.002592  0.019908 -0.017646  
1   -0.039493 -0.068330 -0.092204  
2   -0.002592  0.002864 -0.025930  
3    0.034309  0.022692 -0.009362  
4   -0.002592 -0.031991 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018118  0.044485  
439 -0.011080 -0.046879  0.015491  
440  0.026560  0.044528 -0.025930  
441 -0.039493 -0.004220  0.003064  

[442 rows x 10 columns]

In [20]:
### wgrywam wyczyszczony zbior danych - KLASYFIKACJA
from sklearn.datasets import load_breast_cancer

cancer_X, cancer_y = load_breast_cancer(return_X_y = True, as_frame=True)
cancer_X.head(10)

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   
5        12.45         15.70           82.57      477.1          0.12780   
6        18.25         19.98          119.60     1040.0          0.09463   
7        13.71         20.83           90.20      577.9          0.11890   
8        13.00         21.82           87.50      519.8          0.12730   
9        12.46         24.04           83.97      475.9          0.11860   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760         0.30010              0.14710         0.2419   
1           0.07864         0.08690              0.07017         0.1812   
2           0.15990         0.19740              0.12790         0.2069   
3           0.28390         0.24140              0.10520         0.2597   
4           0.13280         0.19800              0.10430         0.1809   
5           0.17000         0.15780              0.08089         0.2087   
6           0.10900         0.11270              0.07400         0.1794   
7           0.16450         0.09366              0.05985         0.2196   
8           0.19320         0.18590              0.09353         0.2350   
9           0.23960         0.22730              0.08543         0.2030   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   
5                 0.07613  ...         15.47          23.75           103.40   
6                 0.05742  ...         22.88          27.66           153.20   
7                 0.07451  ...         17.06          28.14           110.60   
8                 0.07389  ...         15.49          30.73           106.20   
9                 0.08243  ...         15.09          40.68            97.65   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   
5       741.6            0.1791             0.5249           0.5355   
6      1606.0            0.1442             0.2576           0.3784   
7       897.0            0.1654             0.3682           0.2678   
8       739.3            0.1703             0.5401           0.5390   
9       711.4            0.1853             1.0580           1.1050   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  
5                0.1741          0.3985                  0.12440  
6                0.1932          0.3063                  0.08368  
7                0.1556          0.3196                  0.11510  
8                0.2060          0.4378                  0.10720  
9      

## Wybór modelu

[Lista modeli w scikit learn](https://scikit-learn.org/stable/supervised_learning.html)

![](image/lab03_models_schema.png)

In [22]:
from sklearn.dummy import DummyClassifier

## inicjalizacja
dummy_clf = DummyClassifier()
dummy_clf



DummyClassifier()

In [23]:
### trenowanie modelu - metoda fit
dummy_clf.fit(cancer_X, cancer_y)
dummy_clf

DummyClassifier()

In [24]:
from sklearn.utils.validation import check_is_fitted

In [26]:
check_is_fitted(dummy_clf, msg = True)

In [27]:
## predykcja dla ramki danych

dummy_clf.predict(cancer_X)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [ ]:
## dla klasyfikacji 

dummy_clf.predict_proba

### Zadanie - Wasz własny klasyfikator
**Na razie dla ustawień domyślnych**

![models_comparison](https://scikit-learn.org/stable/_images/sphx_glr_plot_classifier_comparison_001.png)

In [32]:
selected_models = [('LogisticRegression with penalty = none', 'classification', 'breast cancer', "?"),
                   ('LogisticRegression with penalty = l2 ', 'classification', 'breast cancer', "?"),
                   ('LogisticRegression with penalty = l1 ', 'classification', 'breast cancer', "?"),
                   ('LinearRegression', 'regression', 'diabetes', "?"),
                   ('RidgeRegression','regression', 'diabetes', "?"),
                   ('Lasso','regression', 'diabetes', "?"),
                   ('ElasticNet','regression', 'diabetes', "?"),
                   ('SVC', 'classification', 'breast cancer',"?" ),
                   ('LinearSVC', 'classification', 'breast cancer', "?"),
                   ('SVM','regression', 'diabetes', "?"),
                   ('DecisionTreeClassifier', 'classification', 'breast cancer', "?"),
                   ('DecisionTreeRegressor','regression', 'diabetes', "?"),
                   ('RandomForestClassifier', 'classification', 'breast cancer', "?"),
                   ('RandomForestRegressor', 'regression', 'diabetes', "?"),
                   ('ExtraTreesClassifier', 'classification', 'breast cancer', "?"),
                   ('ExtraTreesRegressor', 'regression', 'diabetes', "?"),
                   ('GradientBoostingClassifier', 'classification', 'breast cancer', "?"),
                   ('GradientBoostingRegressor','regression', 'diabetes',"?" )
                  ]

selected_models = pd.DataFrame(selected_models, columns = ['model', 'typ', 'zbior danych', '?'])
selected_models

model             typ   zbior danych  ?
0   LogisticRegression with penalty = none  classification  breast cancer  ?
1    LogisticRegression with penalty = l2   classification  breast cancer  ?
2    LogisticRegression with penalty = l1   classification  breast cancer  ?
3                         LinearRegression      regression       diabetes  ?
4                          RidgeRegression      regression       diabetes  ?
5                                    Lasso      regression       diabetes  ?
6                               ElasticNet      regression       diabetes  ?
7                                      SVC  classification  breast cancer  ?
8                                LinearSVC  classification  breast cancer  ?
9                                      SVM      regression       diabetes  ?
10                  DecisionTreeClassifier  classification  breast cancer  ?
11                   DecisionTreeRegressor      regression       diabetes  ?
12                  RandomForestClassifier  classification  breast cancer  ?
13                   RandomForestRegressor      regression       diabetes  ?
14                    ExtraTreesClassifier  classification  breast cancer  ?
15                     ExtraTreesRegressor      regression       diabetes  ?
16              GradientBoostingClassifier  classification  breast cancer  ?
17               GradientBoostingRegressor      regression       diabetes  ?

In [ ]:
## import modelu

## inicjalizacja

## trenowanie

## predykcja

### Jakich modeli brakuje?

In [ ]:
# !pip install lightgbm
# !pip install catboost
# !pip install xgboost

- [XGBoost](https://xgboost.readthedocs.io/en/stable/python/python_api.html#module-xgboost.sklearn), [przykłady użycia](https://github.com/dmlc/xgboost/tree/master/demo/guide-python)
- [CatBoost](https://catboost.ai/en/docs/concepts/python-usages-examples)

In [34]:
## XGboostCatBoost i LGBM mają takie samo API jak sklearn

from catboost import CatBoostClassifier

catboost_clf = CatBoostClassifier()
# Fit model
catboost_clf.fit(cancer_X, cancer_y)


Learning rate set to 0.008098
0:	learn: 0.6787969	total: 60.3ms	remaining: 1m
1:	learn: 0.6664929	total: 66.6ms	remaining: 33.2s
2:	learn: 0.6539922	total: 72.5ms	remaining: 24.1s
3:	learn: 0.6420210	total: 78.4ms	remaining: 19.5s
4:	learn: 0.6299121	total: 83.5ms	remaining: 16.6s
5:	learn: 0.6181186	total: 87.5ms	remaining: 14.5s
6:	learn: 0.6053391	total: 90.4ms	remaining: 12.8s
7:	learn: 0.5935973	total: 93.6ms	remaining: 11.6s
8:	learn: 0.5814844	total: 96.1ms	remaining: 10.6s
9:	learn: 0.5713399	total: 98.4ms	remaining: 9.74s
10:	learn: 0.5618850	total: 101ms	remaining: 9.07s
11:	learn: 0.5512292	total: 103ms	remaining: 8.48s
12:	learn: 0.5418780	total: 105ms	remaining: 7.98s
13:	learn: 0.5323115	total: 107ms	remaining: 7.54s
14:	learn: 0.5231351	total: 109ms	remaining: 7.17s
15:	learn: 0.5139035	total: 111ms	remaining: 6.84s
16:	learn: 0.5052943	total: 113ms	remaining: 6.55s
17:	learn: 0.4964123	total: 117ms	remaining: 6.4s
18:	learn: 0.4888480	total: 119ms	remaining: 6.16s
19:	l

232:	learn: 0.0626239	total: 579ms	remaining: 1.91s
233:	learn: 0.0624085	total: 582ms	remaining: 1.9s
234:	learn: 0.0620769	total: 584ms	remaining: 1.9s
235:	learn: 0.0618073	total: 586ms	remaining: 1.9s
236:	learn: 0.0615948	total: 589ms	remaining: 1.89s
237:	learn: 0.0612605	total: 591ms	remaining: 1.89s
238:	learn: 0.0608810	total: 593ms	remaining: 1.89s
239:	learn: 0.0604889	total: 596ms	remaining: 1.89s
240:	learn: 0.0602926	total: 599ms	remaining: 1.89s
241:	learn: 0.0600894	total: 603ms	remaining: 1.89s
242:	learn: 0.0598497	total: 605ms	remaining: 1.89s
243:	learn: 0.0596374	total: 607ms	remaining: 1.88s
244:	learn: 0.0594130	total: 610ms	remaining: 1.88s
245:	learn: 0.0591388	total: 612ms	remaining: 1.88s
246:	learn: 0.0589027	total: 614ms	remaining: 1.87s
247:	learn: 0.0586690	total: 616ms	remaining: 1.87s
248:	learn: 0.0583823	total: 618ms	remaining: 1.86s
249:	learn: 0.0581674	total: 620ms	remaining: 1.86s
250:	learn: 0.0580246	total: 622ms	remaining: 1.85s
251:	learn: 0.0

407:	learn: 0.0324261	total: 964ms	remaining: 1.4s
408:	learn: 0.0323153	total: 967ms	remaining: 1.4s
409:	learn: 0.0322187	total: 969ms	remaining: 1.39s
410:	learn: 0.0321108	total: 971ms	remaining: 1.39s
411:	learn: 0.0320542	total: 973ms	remaining: 1.39s
412:	learn: 0.0319708	total: 976ms	remaining: 1.39s
413:	learn: 0.0318846	total: 978ms	remaining: 1.38s
414:	learn: 0.0318069	total: 980ms	remaining: 1.38s
415:	learn: 0.0317444	total: 982ms	remaining: 1.38s
416:	learn: 0.0316366	total: 984ms	remaining: 1.38s
417:	learn: 0.0315456	total: 986ms	remaining: 1.37s
418:	learn: 0.0314094	total: 988ms	remaining: 1.37s
419:	learn: 0.0312954	total: 991ms	remaining: 1.37s
420:	learn: 0.0312143	total: 994ms	remaining: 1.37s
421:	learn: 0.0311563	total: 996ms	remaining: 1.36s
422:	learn: 0.0310481	total: 998ms	remaining: 1.36s
423:	learn: 0.0309411	total: 1s	remaining: 1.36s
424:	learn: 0.0308265	total: 1s	remaining: 1.35s
425:	learn: 0.0306917	total: 1s	remaining: 1.35s
426:	learn: 0.0305871	t

588:	learn: 0.0198502	total: 1.35s	remaining: 941ms
589:	learn: 0.0198215	total: 1.35s	remaining: 940ms
590:	learn: 0.0197815	total: 1.35s	remaining: 938ms
591:	learn: 0.0197447	total: 1.36s	remaining: 936ms
592:	learn: 0.0197062	total: 1.36s	remaining: 935ms
593:	learn: 0.0196598	total: 1.36s	remaining: 932ms
594:	learn: 0.0196170	total: 1.37s	remaining: 930ms
595:	learn: 0.0195636	total: 1.37s	remaining: 928ms
596:	learn: 0.0195176	total: 1.37s	remaining: 926ms
597:	learn: 0.0194736	total: 1.37s	remaining: 923ms
598:	learn: 0.0193969	total: 1.38s	remaining: 921ms
599:	learn: 0.0193524	total: 1.38s	remaining: 918ms
600:	learn: 0.0193075	total: 1.38s	remaining: 916ms
601:	learn: 0.0192613	total: 1.38s	remaining: 913ms
602:	learn: 0.0192308	total: 1.38s	remaining: 911ms
603:	learn: 0.0191787	total: 1.39s	remaining: 908ms
604:	learn: 0.0191318	total: 1.39s	remaining: 906ms
605:	learn: 0.0190711	total: 1.39s	remaining: 903ms
606:	learn: 0.0190217	total: 1.39s	remaining: 901ms
607:	learn: 

769:	learn: 0.0137584	total: 1.73s	remaining: 518ms
770:	learn: 0.0137237	total: 1.74s	remaining: 516ms
771:	learn: 0.0137118	total: 1.74s	remaining: 513ms
772:	learn: 0.0136838	total: 1.74s	remaining: 511ms
773:	learn: 0.0136820	total: 1.74s	remaining: 509ms
774:	learn: 0.0136803	total: 1.74s	remaining: 507ms
775:	learn: 0.0136678	total: 1.75s	remaining: 504ms
776:	learn: 0.0136466	total: 1.75s	remaining: 502ms
777:	learn: 0.0136275	total: 1.75s	remaining: 500ms
778:	learn: 0.0136189	total: 1.75s	remaining: 498ms
779:	learn: 0.0135837	total: 1.75s	remaining: 495ms
780:	learn: 0.0135611	total: 1.76s	remaining: 493ms
781:	learn: 0.0135377	total: 1.76s	remaining: 491ms
782:	learn: 0.0135069	total: 1.76s	remaining: 488ms
783:	learn: 0.0134718	total: 1.76s	remaining: 486ms
784:	learn: 0.0134460	total: 1.76s	remaining: 484ms
785:	learn: 0.0134221	total: 1.77s	remaining: 482ms
786:	learn: 0.0134169	total: 1.77s	remaining: 479ms
787:	learn: 0.0133981	total: 1.77s	remaining: 477ms
788:	learn: 

947:	learn: 0.0106294	total: 2.12s	remaining: 116ms
948:	learn: 0.0106115	total: 2.12s	remaining: 114ms
949:	learn: 0.0106094	total: 2.12s	remaining: 112ms
950:	learn: 0.0106085	total: 2.12s	remaining: 109ms
951:	learn: 0.0106040	total: 2.13s	remaining: 107ms
952:	learn: 0.0105940	total: 2.13s	remaining: 105ms
953:	learn: 0.0105906	total: 2.13s	remaining: 103ms
954:	learn: 0.0105870	total: 2.13s	remaining: 101ms
955:	learn: 0.0105730	total: 2.14s	remaining: 98.3ms
956:	learn: 0.0105636	total: 2.14s	remaining: 96.1ms
957:	learn: 0.0105604	total: 2.14s	remaining: 93.9ms
958:	learn: 0.0105582	total: 2.14s	remaining: 91.6ms
959:	learn: 0.0105570	total: 2.15s	remaining: 89.4ms
960:	learn: 0.0105278	total: 2.15s	remaining: 87.1ms
961:	learn: 0.0105125	total: 2.15s	remaining: 84.9ms
962:	learn: 0.0105092	total: 2.15s	remaining: 82.7ms
963:	learn: 0.0105078	total: 2.15s	remaining: 80.4ms
964:	learn: 0.0104931	total: 2.15s	remaining: 78.2ms
965:	learn: 0.0104785	total: 2.16s	remaining: 75.9ms
9

In [36]:
# Get predicted classes
preds_class = catboost_clf.predict(cancer_X)
print(preds_class[:5])
# Get predicted probabilities for each class
preds_proba = catboost_clf.predict_proba(cancer_X)
print(preds_proba[:5])

[0 0 0 0 0]
[[9.94726460e-01 5.27353955e-03]
 [9.93718957e-01 6.28104309e-03]
 [9.99433066e-01 5.66934322e-04]
 [9.72145935e-01 2.78540649e-02]
 [9.89308373e-01 1.06916275e-02]]


## Hiperparametry

In [37]:
?DummyClassifier

In [ ]:
dummy_clf_2 = DummyClassifier(strategy='uniform')

Model liniowy - z karą Ridge

$$ y_i = f(\alpha + \beta_1 x_{i1} + \beta_2 x_{i2} + \ldots + \beta_p x_{ip})  + \alpha \sum \beta_k ^2 $$

$\beta$ - wyznaczane w wewnętrznej opearcji działania algorytmu - **PARAMETRY**

$\alpha$ -definiowne przez użytkownika w momencie inicjalizacji algorytmu - **HIPERPARAMETR**

### Zadanie - stwórzcie model ze zmienionymi hiperparametrami (dowolnymi). Sprawdźcie ile hiperparametrów ma dany model

Zapiszcie nowy model pod inną nazwą

In [38]:
## inicjalizacja i zmiana hiperparametrów

## trenowanie

## zapisanie predykcji

## Który model wybrać? - miary jakości modeli

In [42]:
from sklearn import metrics
for k, _ in metrics.SCORERS.items():
    print(k)


explained_variance
r2
max_error
neg_median_absolute_error
neg_mean_absolute_error
neg_mean_absolute_percentage_error
neg_mean_squared_error
neg_mean_squared_log_error
neg_root_mean_squared_error
neg_mean_poisson_deviance
neg_mean_gamma_deviance
accuracy
top_k_accuracy
roc_auc
roc_auc_ovr
roc_auc_ovo
roc_auc_ovr_weighted
roc_auc_ovo_weighted
balanced_accuracy
average_precision
neg_log_loss
neg_brier_score
adjusted_rand_score
rand_score
homogeneity_score
completeness_score
v_measure_score
mutual_info_score
adjusted_mutual_info_score
normalized_mutual_info_score
fowlkes_mallows_score
precision
precision_macro
precision_micro
precision_samples
precision_weighted
recall
recall_macro
recall_micro
recall_samples
recall_weighted
f1
f1_macro
f1_micro
f1_samples
f1_weighted
jaccard
jaccard_macro
jaccard_micro
jaccard_samples
jaccard_weighted


### Regresja

1. RMSE
2. R^2

### Klasyfikacja

1. Confusion matrix
2. Accuracy
3. Precision
4. Sensitivity/Recall - czułość
5. Specificity - specyficzność
6. F1
7. Balanced accuracy

8. *Krzywa ROC*
9. *AUC*


### Miary oparte na predykcji klasy

#### Confusion matrix - macierz błędów 

zliczamy ile obserwacji w każdej z grup zostało poprawnie zaklasyfikowanych

![](https://miro.medium.com/max/1838/1*fxiTNIgOyvAombPJx5KGeA.png)

Rodzaje obserwacji:

TP - True Positive - obserwacje poprawnie zaklasyfikowane do klasy pozytywnej

TN - True Negative - obserwacje poprawnie zaklasyfikowane do klasy negatywnej

FP - False Positive - obserwacje niepoprawnie zaklasyfikowane do klasy pozytywnej

FN - False Negative - obserwacje niepoprawnie zaklasyfikowane do klasy negatywnej

#### Accuracy - dokładność

Jaki procent wszystkich obserwacji został dobrze zaklasyfikowany

$$ Accuracy = \frac{TP + TN}{TP+FP+TN+FN} $$

#### Precision function - precyzja

Jaki procent obserwacji zaklasyfikowanych jako pozytywne, faktycznie należy do tej klasy

$$ Precision = \frac{TP}{TP+FP} $$

#### Sensitivity function (recall, TruePositiveRate)

Jaki procent obserwacji pozytywnych został zaklasyfikowany do tej klasy

$$ recall = \frac{TP}{TP+FN} $$

Dla klasy negatywnej odpowiednikiem jest: **Specificity**

#### Specificity function (True negative rate)
Jaki procent obserwacji negatywnych został zaklasyfikowany do tej klasy

$$ Specificity =  \frac{TN}{TN+FP} $$

#### F1

Średnia harmoniczna precyzji i recall
$$ F_1 = 2* \frac{precision \times recall}{precision + recall}$$

In [99]:
from sklearn.ensemble import RandomForestClassifier


rf_clf = RandomForestClassifier(n_estimators=10)
rf_clf.fit(cancer_X, cancer_y)
predicted_class = rf_clf.predict(cancer_X)
predicted_prob = rf_clf.predict_proba(cancer_X)

In [100]:
from sklearn.metrics import accuracy_score
accuracy_score(cancer_y, predicted_class)

0.9964850615114236

### Miary oparte na predykcji prawdopodobieństwa

#### Krzywa ROCR

Ten wykres jest funkcją punktu odcięcia - jeśli model przewidzi prawdopodobieństwo powyżej tej wartości to klasyfikujemy ją do klasy pozytywnej. Dla punktów odcięcia wyznaczne jest False Positive Rate (x) vs. True Positive Rate (y).

[Youtube](https://www.youtube.com/watch?v=4jRBRDbJemM)

<div>
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Roc-draft-xkcd-style.svg/1280px-Roc-draft-xkcd-style.svg.png" width="500" style="float:middle"/>
</div>

#### AUC 

Pole pod krzywą ROC. AUC $\in (0.5; 1]$
$0.5$ przyjmuje losowy klasyfikator

In [102]:
from sklearn.metrics import roc_auc_score
roc_auc_score(cancer_y, predicted_prob[:,1])

0.9999669679192432

### Zadanie - Sprawdź jakość modeli, które wytrenowałeś? Czy po zmianie hiperparametrów uzyskałeś lepszy wynik?



In [ ]:
### TODO

## Co z generalizacją modelu? Czy uzyskamy podobny wynik na nowych danych?

### Schematy walidacji 


 #### 1. Podział na zbiór treningowy/testowy ewentualnie walidacyjny

In [52]:
from sklearn.model_selection import train_test_split

In [54]:
cancer_X_train, cancer_X_test, cancer_y_train, cancer_y_test = train_test_split(cancer_X, 
                                                                                cancer_y,
                                                                                random_state=123, train_size=0.8)

In [55]:
print('All data:',cancer_X.shape)
print('Train data:', cancer_X_train.shape)

All data: (569, 30)
Train data: (455, 30)



 
 #### 2. Kroswlidacja
 
 
 ![](image/lab3_crossvalidation.png)
 
Aby lepiej oceniać stabilność jakośni modeli na danych treningowych stosuje się kroswalidację - cały zbiór danych treningowy dzielimy na $k$ - podzbiorów. W każdej iteracji uczymy algorytm na $k-1$ podzbiorach a testujemy na pozostałym jednym zbiorze danych. 

Jako ocenę jakości modeli możemy stosować każdą z wyżej wymienionych miar.

Jeśli model jest dobrze przygotowany to błąd, który uzyskamy na zbiorze testowym (który nie był wykorzystywany w kroswalidacji) powiniem być zbliżony do średnigo błędu z kroswalidacji.

#### 3. Bootstrap

![](image/bootstrap.png)

### 4. To nie wszystko! - te metody nie są idealne

In [56]:
from sklearn.model_selection import cross_validate
from sklearn.ensemble import RandomForestClassifier

In [57]:
from sklearn.model_selection import cross_validate
from sklearn.ensemble import RandomForestClassifier
# parametr cv  - możemy podać liczę podzialow, albo konkretny podzial po indeksach ramki danych 
# scoring - jakiej metryki uzyc do oceny

rf_clf = RandomForestClassifier(n_estimators=10)


cv_results = cross_validate(rf_clf, cancer_X, cancer_y, cv=3)

print(cv_results.keys())

print(cv_results['test_score'])


dict_keys(['fit_time', 'score_time', 'test_score'])
[0.93684211 0.96315789 0.94179894]


In [58]:
# Mozemy podawac kilka metryk, ktore beda sprawdzane na zbiorze testowym i treningowym (scoring)
# Mozemy zachowywac tez wyniki na zbiorze treningowym (return_train_score)

cv_results = cross_validate(rf_clf, cancer_X, cancer_y, cv=3, 
                            return_train_score = True,scoring =  ['accuracy', 'roc_auc'])
print(cv_results.keys())


print(cv_results['test_accuracy'])

dict_keys(['fit_time', 'score_time', 'test_accuracy', 'train_accuracy', 'test_roc_auc', 'train_roc_auc'])
[0.94736842 0.95789474 0.94179894]


## Jak wybrać najlepszy model? Optymalizacja hiperparametrów

## 1. Grid search
## 2. Random search

![](https://developer.qualcomm.com/sites/default/files/attachments/learning_resources_03-05.png)

## Który metoda jest skuteczniejsza?

In [60]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.svm import SVC

In [ ]:
## Gridsearch

In [63]:
parameters = {'kernel':('linear', 'rbf'), 'C':[1, 10]}
svc = SVC()
## domyslny parametr cv = 5

clf = GridSearchCV(svc, parameters, scoring = 'roc_auc', return_train_score=True)
clf.fit(cancer_X, cancer_y)

GridSearchCV(estimator=SVC(),
             param_grid={'C': [1, 10], 'kernel': ('linear', 'rbf')},
             return_train_score=True, scoring='roc_auc')

In [64]:
clf.cv_results_

{'mean_fit_time': array([1.35942035, 0.0061347 , 4.09353561, 0.00556936]),
 'std_fit_time': array([5.45222929e-01, 1.18195072e-04, 7.91584667e-01, 1.53517099e-04]),
 'mean_score_time': array([0.00305319, 0.00360637, 0.0029912 , 0.00336614]),
 'std_score_time': array([4.98868302e-05, 3.06177730e-05, 1.08494862e-05, 7.68342259e-05]),
 'param_C': masked_array(data=[1, 1, 10, 10],
              mask=[False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['linear', 'rbf', 'linear', 'rbf'],
              mask=[False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'linear'},
  {'C': 1, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'}],
 'split0_test_score': array([0.99115624, 0.95447101, 0.9901736 , 0.96364232]),
 'split1_test_score': array([0.99312152, 0.97772683, 0.99115624, 0.98788077]),
 'split2_test_score': array([0.99801587, 0.98148148, 0

In [66]:
clf.cv_results_['params']

[{'C': 1, 'kernel': 'linear'},
 {'C': 1, 'kernel': 'rbf'},
 {'C': 10, 'kernel': 'linear'},
 {'C': 10, 'kernel': 'rbf'}]

In [69]:
clf.cv_results_['mean_test_score']

array([0.99109413, 0.97396192, 0.98951435, 0.97993592])

In [ ]:
## Random search
import scipy.stats

In [78]:
import scipy.stats

## w liscie parametrow do testowania musimy powiedziec z jakim rozkladem wartosci powinny byc losowane
parameters_distribution = {'C': scipy.stats.uniform(0,1), 'gamma': scipy.stats.expon(scale=.1),
  'kernel': ['rbf', 'linear'], 'class_weight':['balanced', None]}

clf_random = RandomizedSearchCV(svc, parameters_distribution, random_state=0)
clf_random.fit(cancer_X, cancer_y)

RandomizedSearchCV(estimator=SVC(),
                   param_distributions={'C': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7fdeae8f47c0>,
                                        'class_weight': ['balanced', None],
                                        'gamma': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7fdeae80ccd0>,
                                        'kernel': ['rbf', 'linear']},
                   random_state=0)

In [80]:
clf_random.cv_results_['params']

[{'C': 0.5488135039273248,
  'class_weight': None,
  'gamma': 0.18596042409118513,
  'kernel': 'linear'},
 {'C': 0.5448831829968969,
  'class_weight': None,
  'gamma': 0.09770064274254157,
  'kernel': 'rbf'},
 {'C': 0.4375872112626925,
  'class_weight': 'balanced',
  'gamma': 0.005838467078070335,
  'kernel': 'rbf'},
 {'C': 0.3834415188257777,
  'class_weight': 'balanced',
  'gamma': 0.16722112126272706,
  'kernel': 'rbf'},
 {'C': 0.5680445610939323,
  'class_weight': None,
  'gamma': 0.18083692319941533,
  'kernel': 'rbf'},
 {'C': 0.08712929970154071,
  'class_weight': None,
  'gamma': 0.04592481411779334,
  'kernel': 'linear'},
 {'C': 0.7781567509498505,
  'class_weight': None,
  'gamma': 0.2040892272036123,
  'kernel': 'linear'},
 {'C': 0.7991585642167236,
  'class_weight': None,
  'gamma': 0.07349644192364166,
  'kernel': 'linear'},
 {'C': 0.11827442586893322,
  'class_weight': 'balanced',
  'gamma': 0.08723211970403807,
  'kernel': 'linear'},
 {'C': 0.9446689170495839,
  'class_we

In [81]:
clf_random.cv_results_['mean_test_score']

array([0.94378202, 0.6274181 , 0.64839311, 0.47784506, 0.6274181 ,
       0.94553641, 0.94730632, 0.94730632, 0.94553641, 0.94729079])

## 3. Optymalizacja Bayesowska

<img src="image/BO.gif" width="750" align="center">

In [86]:
# !pip install scikit-optimize

In [85]:
import scipy, skopt

In [88]:
?RandomForestClassifier


In [104]:
## zdefiniowanie przedstrzeni przeszukiwań -- skopt.space

search_spaces = {
        'criterion': ['gini', 'entropy'],
        'n_estimators': skopt.space.space.Integer(1, 500),
        'max_depth': skopt.space.space.Integer(2, 10)
}



In [98]:

rf = RandomForestClassifier()
opt_1 = skopt.BayesSearchCV(
        estimator=rf,
        search_spaces=search_spaces,
        scoring='roc_auc',
        n_jobs=4,
        n_iter=10,
        verbose=0,
        random_state=1
    )
opt_1.fit(cancer_X, cancer_y)

BayesSearchCV(estimator=RandomForestClassifier(), n_iter=10, n_jobs=4,
              random_state=1, scoring='roc_auc',
              search_spaces={'criterion': ['gini', 'entropy'],
                             'max_depth': Integer(low=2, high=10, prior='uniform', transform='normalize'),
                             'n_estimators': Integer(low=1, high=500, prior='uniform', transform='normalize')})

# Praca domowa 2 - termin oddania kolejna środa, do końca dnia

Dla zbioru danych opracowanego w poprzedniej pracy domowej dopasować wybrany model uczenia maszynowego i go zwdalidować (AUC i jedna inna wybrana metryka) dla domyślnych hiperparametrów. 
W kolejnym kroku należy przeprowadzić optymalizację hiperparametrów metodami:
1. ręczna zmiana hiperparametrów
2. random search
3. grid search
4. optymalizacja bayesowska

Jeśli dla opracowanego zbioru danych wybrany algorytm ML nie działa, należy odpowiednio zmodyfikować zbiór danych.

Rozwiązanie należy przygotować w formie raportu (kod z komentarzami) w formacie `ipnyb` lub `.html` i umieścić w foldarze `homeworks/hw2/NazwiskoImie`.

