# Laboratorium 3

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from IPython.display import Image
from IPython.core.display import HTML 
import seaborn as sns

In [2]:
# ! pip install --user --upgrade scikit-learn

## Wcześniej przeprowadzony preprocessing

In [3]:
### wgrywam wyczyszczony zbior danych - REGRESJA
from sklearn.datasets import load_diabetes

diabetes_X, diabetes_y = load_diabetes(return_X_y = True, as_frame=True)

diabetes_X

In [4]:
diabetes_y

0      151.0
1       75.0
2      141.0
3      206.0
4      135.0
       ...  
437    178.0
438    104.0
439    132.0
440    220.0
441     57.0
Name: target, Length: 442, dtype: float64

In [5]:
### wgrywam wyczyszczony zbior danych - KLASYFIKACJA
from sklearn.datasets import load_breast_cancer

cancer_X, cancer_y = load_breast_cancer(return_X_y = True, as_frame=True)
cancer_X.head(10)

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   
5        12.45         15.70           82.57      477.1          0.12780   
6        18.25         19.98          119.60     1040.0          0.09463   
7        13.71         20.83           90.20      577.9          0.11890   
8        13.00         21.82           87.50      519.8          0.12730   
9        12.46         24.04           83.97      475.9          0.11860   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760         0.30010              0.14710         0.2419   
1           0.07864         0.08690              0.07017         0.1812   
2           0.15990         0.19740              0.12790         0.2069   
3           0.28390         0.24140              0.10520         0.2597   
4           0.13280         0.19800              0.10430         0.1809   
5           0.17000         0.15780              0.08089         0.2087   
6           0.10900         0.11270              0.07400         0.1794   
7           0.16450         0.09366              0.05985         0.2196   
8           0.19320         0.18590              0.09353         0.2350   
9           0.23960         0.22730              0.08543         0.2030   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   
5                 0.07613  ...         15.47          23.75           103.40   
6                 0.05742  ...         22.88          27.66           153.20   
7                 0.07451  ...         17.06          28.14           110.60   
8                 0.07389  ...         15.49          30.73           106.20   
9                 0.08243  ...         15.09          40.68            97.65   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   
5       741.6            0.1791             0.5249           0.5355   
6      1606.0            0.1442             0.2576           0.3784   
7       897.0            0.1654             0.3682           0.2678   
8       739.3            0.1703             0.5401           0.5390   
9       711.4            0.1853             1.0580           1.1050   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  
5                0.1741          0.3985                  0.12440  
6                0.1932          0.3063                  0.08368  
7                0.1556          0.3196                  0.11510  
8                0.2060          0.4378                  0.10720  
9      

In [6]:
cancer_y.unique()

array([0, 1])

## Wybór modelu

[Lista modeli w scikit learn](https://scikit-learn.org/stable/supervised_learning.html)

![](image/lab03_models_schema.png)

In [7]:
from sklearn.dummy import DummyClassifier

## inicjalizacja
dummy_clf = DummyClassifier()
dummy_clf



DummyClassifier()

In [8]:
### trenowanie modelu - metoda fit
dummy_clf.fit(cancer_X, cancer_y)

DummyClassifier()

In [9]:
from sklearn.utils.validation import check_is_fitted

In [10]:
check_is_fitted(dummy_clf, msg = True)

In [11]:
## predykcja dla ramki danych
dummy_clf.predict(cancer_X)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [12]:
## dla klasyfikacji 

dummy_clf.predict_proba(cancer_X)

array([[0.37258348, 0.62741652],
       [0.37258348, 0.62741652],
       [0.37258348, 0.62741652],
       ...,
       [0.37258348, 0.62741652],
       [0.37258348, 0.62741652],
       [0.37258348, 0.62741652]])

### Zadanie - Wasz własny klasyfikator
**Na razie dla ustawień domyślnych**

![models_comparison](https://scikit-learn.org/stable/_images/sphx_glr_plot_classifier_comparison_001.png)

In [13]:
selected_models = [('LogisticRegression with penalty = none', 'classification', 'breast cancer', "?"),
                   ('LogisticRegression with penalty = l2 ', 'classification', 'breast cancer', "?"),
                   ('LogisticRegression with penalty = l1 ', 'classification', 'breast cancer', "?"),
                   ('LinearRegression', 'regression', 'diabetes', "?"),
                   ('RidgeRegression','regression', 'diabetes', "?"),
                   ('Lasso','regression', 'diabetes', "?"),
                   ('ElasticNet','regression', 'diabetes', "?"),
                   ('SVC', 'classification', 'breast cancer',"?" ),
                   ('LinearSVC', 'classification', 'breast cancer', "?"),
                   ('SVM','regression', 'diabetes', "?"),
                   ('DecisionTreeClassifier', 'classification', 'breast cancer', "?"),
                   ('DecisionTreeRegressor','regression', 'diabetes', "?"),
                   ('RandomForestClassifier', 'classification', 'breast cancer', "?"),
                   ('RandomForestRegressor', 'regression', 'diabetes', "?"),
                   ('ExtraTreesClassifier', 'classification', 'breast cancer', "?"),
                   ('ExtraTreesRegressor', 'regression', 'diabetes', "?"),
                   ('GradientBoostingClassifier', 'classification', 'breast cancer', "?"),
                   ('GradientBoostingRegressor','regression', 'diabetes',"?" )
                  ]

selected_models = pd.DataFrame(selected_models, columns = ['model', 'typ', 'zbior danych', '?'])
selected_models

model             typ   zbior danych  ?
0   LogisticRegression with penalty = none  classification  breast cancer  ?
1    LogisticRegression with penalty = l2   classification  breast cancer  ?
2    LogisticRegression with penalty = l1   classification  breast cancer  ?
3                         LinearRegression      regression       diabetes  ?
4                          RidgeRegression      regression       diabetes  ?
5                                    Lasso      regression       diabetes  ?
6                               ElasticNet      regression       diabetes  ?
7                                      SVC  classification  breast cancer  ?
8                                LinearSVC  classification  breast cancer  ?
9                                      SVM      regression       diabetes  ?
10                  DecisionTreeClassifier  classification  breast cancer  ?
11                   DecisionTreeRegressor      regression       diabetes  ?
12                  RandomForestClassifier  classification  breast cancer  ?
13                   RandomForestRegressor      regression       diabetes  ?
14                    ExtraTreesClassifier  classification  breast cancer  ?
15                     ExtraTreesRegressor      regression       diabetes  ?
16              GradientBoostingClassifier  classification  breast cancer  ?
17               GradientBoostingRegressor      regression       diabetes  ?

In [14]:
## import modelu
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import _is_constant_feature
## inicjalizacja
lg = LogisticRegression()
## trenowanie
lg.fit(cancer_X, cancer_y)
## predykcja
lg.predict_proba(cancer_X)

ImportError: cannot import name '_is_constant_feature' from 'sklearn.preprocessing' (/home/kasia/.local/lib/python3.8/site-packages/sklearn/preprocessing/__init__.py)

### Jakich modeli brakuje?

In [15]:
## XGboost, CatBoost i LGBM mają takie samo API jak sklearn

from catboost import CatBoostClassifier

catboost_clf = CatBoostClassifier()
# Fit model
catboost_clf.fit(cancer_X, cancer_y)

Learning rate set to 0.008098
0:	learn: 0.6787969	total: 50.1ms	remaining: 50s
1:	learn: 0.6664929	total: 52.1ms	remaining: 26s
2:	learn: 0.6539922	total: 54.1ms	remaining: 18s
3:	learn: 0.6420210	total: 57ms	remaining: 14.2s
4:	learn: 0.6299121	total: 59ms	remaining: 11.7s
5:	learn: 0.6181186	total: 61ms	remaining: 10.1s
6:	learn: 0.6053391	total: 63ms	remaining: 8.93s
7:	learn: 0.5935973	total: 64.9ms	remaining: 8.05s
8:	learn: 0.5814844	total: 67.1ms	remaining: 7.39s
9:	learn: 0.5713399	total: 69.2ms	remaining: 6.85s
10:	learn: 0.5618850	total: 71.2ms	remaining: 6.4s
11:	learn: 0.5512292	total: 73.2ms	remaining: 6.03s
12:	learn: 0.5418780	total: 75.4ms	remaining: 5.72s
13:	learn: 0.5323115	total: 77.4ms	remaining: 5.45s
14:	learn: 0.5231351	total: 79.3ms	remaining: 5.21s
15:	learn: 0.5139035	total: 81.2ms	remaining: 4.99s
16:	learn: 0.5052943	total: 83.1ms	remaining: 4.81s
17:	learn: 0.4964123	total: 85ms	remaining: 4.64s
18:	learn: 0.4888480	total: 86.9ms	remaining: 4.49s
19:	learn

161:	learn: 0.0947437	total: 386ms	remaining: 2s
162:	learn: 0.0943214	total: 388ms	remaining: 1.99s
163:	learn: 0.0938264	total: 390ms	remaining: 1.99s
164:	learn: 0.0931152	total: 392ms	remaining: 1.98s
165:	learn: 0.0925335	total: 394ms	remaining: 1.98s
166:	learn: 0.0919788	total: 396ms	remaining: 1.98s
167:	learn: 0.0912896	total: 398ms	remaining: 1.97s
168:	learn: 0.0907471	total: 400ms	remaining: 1.97s
169:	learn: 0.0902490	total: 402ms	remaining: 1.96s
170:	learn: 0.0895613	total: 405ms	remaining: 1.96s
171:	learn: 0.0886617	total: 407ms	remaining: 1.96s
172:	learn: 0.0880755	total: 409ms	remaining: 1.96s
173:	learn: 0.0875295	total: 411ms	remaining: 1.95s
174:	learn: 0.0869803	total: 413ms	remaining: 1.95s
175:	learn: 0.0863835	total: 415ms	remaining: 1.94s
176:	learn: 0.0857112	total: 418ms	remaining: 1.94s
177:	learn: 0.0850477	total: 420ms	remaining: 1.94s
178:	learn: 0.0843779	total: 422ms	remaining: 1.94s
179:	learn: 0.0838587	total: 424ms	remaining: 1.93s
180:	learn: 0.0

332:	learn: 0.0415480	total: 770ms	remaining: 1.54s
333:	learn: 0.0414020	total: 773ms	remaining: 1.54s
334:	learn: 0.0412716	total: 777ms	remaining: 1.54s
335:	learn: 0.0411402	total: 779ms	remaining: 1.54s
336:	learn: 0.0410265	total: 781ms	remaining: 1.54s
337:	learn: 0.0409131	total: 784ms	remaining: 1.53s
338:	learn: 0.0407614	total: 786ms	remaining: 1.53s
339:	learn: 0.0405800	total: 788ms	remaining: 1.53s
340:	learn: 0.0404342	total: 791ms	remaining: 1.53s
341:	learn: 0.0403345	total: 793ms	remaining: 1.53s
342:	learn: 0.0401982	total: 796ms	remaining: 1.52s
343:	learn: 0.0400163	total: 799ms	remaining: 1.52s
344:	learn: 0.0397867	total: 801ms	remaining: 1.52s
345:	learn: 0.0396680	total: 803ms	remaining: 1.52s
346:	learn: 0.0395561	total: 805ms	remaining: 1.51s
347:	learn: 0.0393430	total: 810ms	remaining: 1.52s
348:	learn: 0.0392437	total: 812ms	remaining: 1.51s
349:	learn: 0.0391404	total: 814ms	remaining: 1.51s
350:	learn: 0.0389904	total: 816ms	remaining: 1.51s
351:	learn: 

492:	learn: 0.0253915	total: 1.16s	remaining: 1.19s
493:	learn: 0.0253128	total: 1.16s	remaining: 1.19s
494:	learn: 0.0252441	total: 1.16s	remaining: 1.18s
495:	learn: 0.0251828	total: 1.16s	remaining: 1.18s
496:	learn: 0.0251000	total: 1.17s	remaining: 1.18s
497:	learn: 0.0250496	total: 1.17s	remaining: 1.18s
498:	learn: 0.0249939	total: 1.17s	remaining: 1.17s
499:	learn: 0.0249306	total: 1.17s	remaining: 1.17s
500:	learn: 0.0248570	total: 1.17s	remaining: 1.17s
501:	learn: 0.0248093	total: 1.18s	remaining: 1.17s
502:	learn: 0.0247511	total: 1.18s	remaining: 1.16s
503:	learn: 0.0246848	total: 1.18s	remaining: 1.16s
504:	learn: 0.0246031	total: 1.18s	remaining: 1.16s
505:	learn: 0.0245530	total: 1.19s	remaining: 1.16s
506:	learn: 0.0244917	total: 1.19s	remaining: 1.15s
507:	learn: 0.0244391	total: 1.19s	remaining: 1.15s
508:	learn: 0.0243874	total: 1.19s	remaining: 1.15s
509:	learn: 0.0243068	total: 1.19s	remaining: 1.15s
510:	learn: 0.0242509	total: 1.2s	remaining: 1.15s
511:	learn: 0

676:	learn: 0.0164316	total: 1.54s	remaining: 736ms
677:	learn: 0.0164113	total: 1.55s	remaining: 735ms
678:	learn: 0.0163739	total: 1.55s	remaining: 733ms
679:	learn: 0.0163335	total: 1.55s	remaining: 731ms
680:	learn: 0.0162926	total: 1.55s	remaining: 728ms
681:	learn: 0.0162639	total: 1.56s	remaining: 726ms
682:	learn: 0.0162374	total: 1.56s	remaining: 724ms
683:	learn: 0.0162152	total: 1.56s	remaining: 721ms
684:	learn: 0.0161970	total: 1.56s	remaining: 719ms
685:	learn: 0.0161701	total: 1.56s	remaining: 717ms
686:	learn: 0.0161215	total: 1.57s	remaining: 714ms
687:	learn: 0.0160839	total: 1.57s	remaining: 712ms
688:	learn: 0.0160674	total: 1.57s	remaining: 709ms
689:	learn: 0.0160544	total: 1.57s	remaining: 707ms
690:	learn: 0.0159921	total: 1.58s	remaining: 705ms
691:	learn: 0.0159624	total: 1.58s	remaining: 703ms
692:	learn: 0.0159284	total: 1.58s	remaining: 700ms
693:	learn: 0.0158951	total: 1.58s	remaining: 698ms
694:	learn: 0.0158586	total: 1.58s	remaining: 696ms
695:	learn: 

846:	learn: 0.0122231	total: 1.93s	remaining: 349ms
847:	learn: 0.0121899	total: 1.93s	remaining: 347ms
848:	learn: 0.0121837	total: 1.94s	remaining: 344ms
849:	learn: 0.0121313	total: 1.94s	remaining: 342ms
850:	learn: 0.0121071	total: 1.94s	remaining: 340ms
851:	learn: 0.0120870	total: 1.94s	remaining: 337ms
852:	learn: 0.0120613	total: 1.95s	remaining: 335ms
853:	learn: 0.0120347	total: 1.95s	remaining: 333ms
854:	learn: 0.0120046	total: 1.95s	remaining: 331ms
855:	learn: 0.0119849	total: 1.95s	remaining: 328ms
856:	learn: 0.0119829	total: 1.95s	remaining: 326ms
857:	learn: 0.0119558	total: 1.96s	remaining: 324ms
858:	learn: 0.0119397	total: 1.96s	remaining: 321ms
859:	learn: 0.0119102	total: 1.96s	remaining: 319ms
860:	learn: 0.0118972	total: 1.96s	remaining: 317ms
861:	learn: 0.0118818	total: 1.96s	remaining: 315ms
862:	learn: 0.0118685	total: 1.97s	remaining: 312ms
863:	learn: 0.0118496	total: 1.97s	remaining: 310ms
864:	learn: 0.0118287	total: 1.97s	remaining: 308ms
865:	learn: 

In [30]:
# Get predicted classes
preds_class = catboost_clf.predict(cancer_X)
print(preds_class[:5])
# Get predicted probabilities for each class
preds_proba = catboost_clf.predict_proba(cancer_X)
print(preds_proba[:5])

[0 0 0 0 0]
[[9.94726460e-01 5.27353955e-03]
 [9.93718957e-01 6.28104309e-03]
 [9.99433066e-01 5.66934322e-04]
 [9.72145935e-01 2.78540649e-02]
 [9.89308373e-01 1.06916275e-02]]


In [3]:
#


## Hiperparametry

In [31]:
?DummyClassifier

In [ ]:
dummy_clf_2 = DummyClassifier(strategy='uniform')

Model liniowy - z karą Ridge

$$ y_i = f(\alpha + \beta_1 x_{i1} + \beta_2 x_{i2} + \ldots + \beta_p x_{ip})  + \alpha \sum \beta_k ^2 $$

$\beta$ - wyznaczane w wewnętrznej opearcji działania algorytmu - **PARAMETRY**

$\alpha$ -definiowne przez użytkownika w momencie inicjalizacji algorytmu - **HIPERPARAMETR**

### Zadanie - stwórzcie model ze zmienionymi hiperparametrami (dowolnymi). Sprawdźcie ile hiperparametrów ma dany model

Zapiszcie nowy model pod inną nazwą

In [18]:
## inicjalizacja i zmiana hiperparametrów

?LogisticRegression

lg_2 = LogisticRegression(penalty= 'none')

## trenowanie
lg_2.fit(cancer_X,  cancer_y)

## zapisanie predykcji
lg_2.predict(cancer_X)

/home/kasia/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,

## Który model wybrać? - miary jakości modeli

In [19]:
from sklearn import metrics
for k, _ in metrics.SCORERS.items():
    print(k)


explained_variance
r2
max_error
neg_median_absolute_error
neg_mean_absolute_error
neg_mean_absolute_percentage_error
neg_mean_squared_error
neg_mean_squared_log_error
neg_root_mean_squared_error
neg_mean_poisson_deviance
neg_mean_gamma_deviance
accuracy
top_k_accuracy
roc_auc
roc_auc_ovr
roc_auc_ovo
roc_auc_ovr_weighted
roc_auc_ovo_weighted
balanced_accuracy
average_precision
neg_log_loss
neg_brier_score
adjusted_rand_score
rand_score
homogeneity_score
completeness_score
v_measure_score
mutual_info_score
adjusted_mutual_info_score
normalized_mutual_info_score
fowlkes_mallows_score
precision
precision_macro
precision_micro
precision_samples
precision_weighted
recall
recall_macro
recall_micro
recall_samples
recall_weighted
f1
f1_macro
f1_micro
f1_samples
f1_weighted
jaccard
jaccard_macro
jaccard_micro
jaccard_samples
jaccard_weighted


### Regresja

- RMSE
- MAE
- R^2

### Klasyfikacja

- confusion matrix
- accuracy
- precision
- recall
- f1
- krzywa ROC
- AUC
- współczynnik giniego


### Miary oparte na predykcji klasy

#### Confusion matrix - macierz błędów 

zliczamy ile obserwacji w każdej z grup zostało poprawnie zaklasyfikowanych

![](https://miro.medium.com/max/1838/1*fxiTNIgOyvAombPJx5KGeA.png)

Rodzaje obserwacji:

TP - True Positive - obserwacje poprawnie zaklasyfikowane do klasy pozytywnej

TN - True Negative - obserwacje poprawnie zaklasyfikowane do klasy negatywnej

FP - False Positive - obserwacje niepoprawnie zaklasyfikowane do klasy pozytywnej

FN - False Negative - obserwacje niepoprawnie zaklasyfikowane do klasy negatywnej

#### Accuracy - dokładność

Jaki procent wszystkich obserwacji został dobrze zaklasyfikowany

$$ Accuracy = \frac{TP + TN}{TP+FP+TN+FN} $$

#### Precision function - precyzja

Jaki procent obserwacji zaklasyfikowanych jako pozytywne, faktycznie należy do tej klasy

$$ Precision = \frac{TP}{TP+FP} $$

#### Sensitivity function (recall, TruePositiveRate)

Jaki procent obserwacji pozytywnych został zaklasyfikowany do tej klasy

$$ recall = \frac{TP}{TP+FN} $$

Dla klasy negatywnej odpowiednikiem jest: **Specificity**

#### Specificity function (True negative rate)
Jaki procent obserwacji negatywnych został zaklasyfikowany do tej klasy

$$ Specificity =  \frac{TN}{TN+FP} $$

#### F1

Średnia harmoniczna precyzji i recall
$$ F_1 = 2* \frac{precision \times recall}{precision + recall}$$

In [20]:
from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier(n_estimators=10)
rf_clf.fit(cancer_X, cancer_y)
predicted_class = rf_clf.predict(cancer_X)
predicted_prob = rf_clf.predict_proba(cancer_X)

In [26]:
from sklearn.metrics import accuracy_score, precision_score, f1_score
accuracy_score(cancer_y, predicted_class)

1.0

In [27]:
precision_score(cancer_y, predicted_class)
f1_score(cancer_y, predicted_class)

1.0

### Miary oparte na predykcji prawdopodobieństwa

#### Krzywa ROCR

Ten wykres jest funkcją punktu odcięcia - jeśli model przewidzi prawdopodobieństwo powyżej tej wartości to klasyfikujemy ją do klasy pozytywnej. Dla punktów odcięcia wyznaczne jest False Positive Rate (x) vs. True Positive Rate (y).

[Youtube](https://www.youtube.com/watch?v=4jRBRDbJemM)

<div>
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Roc-draft-xkcd-style.svg/1280px-Roc-draft-xkcd-style.svg.png" width="500" style="float:middle"/>
</div>

#### AUC 

Pole pod krzywą ROC. AUC $\in (0.5; 1]$
$0.5$ przyjmuje losowy klasyfikator

In [28]:
from sklearn.metrics import roc_auc_score
roc_auc_score(cancer_y, predicted_prob[:,1])

1.0

### Zadanie - Sprawdź jakość modeli, które wytrenowałeś? Czy po zmianie hiperparametrów uzyskałeś lepszy wynik?



In [ ]:
### TODO

## Co z generalizacją modelu? Czy uzyskamy podobny wynik na nowych danych?

### Schematy walidacji 


 #### 1. Podział na zbiór treningowy/testowy ewentualnie walidacyjny

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
cancer_X_train, cancer_X_test, cancer_y_train, cancer_y_test = train_test_split(cancer_X, cancer_y, 
                                                                                random_state=123, shuffle=True,
                                                                                train_size=0.8)

In [31]:
print('All data:',cancer_X.shape)
print('Train data:', cancer_X_train.shape)

All data: (569, 30)
Train data: (455, 30)



 
 #### 2. Kroswlidacja
 
 
 ![](image/lab3_crossvalidation.png)
 
Aby lepiej oceniać stabilność jakośni modeli na danych treningowych stosuje się kroswalidację - cały zbiór danych treningowy dzielimy na $k$ - podzbiorów. W każdej iteracji uczymy algorytm na $k-1$ podzbiorach a testujemy na pozostałym jednym zbiorze danych. 

Jako ocenę jakości modeli możemy stosować każdą z wyżej wymienionych miar.

Jeśli model jest dobrze przygotowany to błąd, który uzyskamy na zbiorze testowym (który nie był wykorzystywany w kroswalidacji) powiniem być zbliżony do średnigo błędu z kroswalidacji.

#### 3. Bootstrap

![](image/bootstrap.png)

### 4. To nie wszystko! - te metody nie są idealne

In [32]:
from sklearn.model_selection import cross_validate
from sklearn.ensemble import RandomForestClassifier

In [33]:


rf_clf = RandomForestClassifier(n_estimators=10)


cv_results = cross_validate(rf_clf, cancer_X, cancer_y, cv=3)

print(cv_results.keys())

print(cv_results['test_score'])



dict_keys(['fit_time', 'score_time', 'test_score'])
[0.93684211 0.95263158 0.93121693]


In [34]:
cv_results = cross_validate(rf_clf, cancer_X, cancer_y, cv=3, 
                            return_train_score = True,scoring =  ['accuracy', 'roc_auc'])
print(cv_results.keys())


print(cv_results['test_accuracy'])

dict_keys(['fit_time', 'score_time', 'test_accuracy', 'train_accuracy', 'test_roc_auc', 'train_roc_auc'])
[0.92631579 0.95789474 0.97883598]


In [35]:
cv_results

{'fit_time': array([0.02070522, 0.02025747, 0.01996279]),
 'score_time': array([0.00811315, 0.0073278 , 0.00705099]),
 'test_accuracy': array([0.92631579, 0.95789474, 0.97883598]),
 'train_accuracy': array([0.99736148, 0.98944591, 0.99736842]),
 'test_roc_auc': array([0.97757131, 0.98780921, 0.99531813]),
 'train_roc_auc': array([0.9999106 , 0.99976161, 1.        ])}

## Jak wybrać najlepszy model? Optymalizacja hiperparametrów

## 1. Grid search
## 2. Random search

![](https://developer.qualcomm.com/sites/default/files/attachments/learning_resources_03-05.png)

## Który metoda jest skuteczniejsza?

In [36]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.svm import SVC

In [38]:
parameters = {'kernel':('linear', 'rbf'), 'C':[1, 10]}
svc = SVC()
## domyslny parametr cv = 5

clf = GridSearchCV(svc, parameters, scoring = 'roc_auc', return_train_score=True)
clf.fit(cancer_X, cancer_y)

GridSearchCV(estimator=SVC(),
             param_grid={'C': [1, 10], 'kernel': ('linear', 'rbf')},
             return_train_score=True, scoring='roc_auc')

In [39]:
clf.cv_results_

{'mean_fit_time': array([1.34401755, 0.00597548, 4.12602267, 0.00539622]),
 'std_fit_time': array([5.32265530e-01, 1.12054906e-04, 7.96093804e-01, 8.16388664e-05]),
 'mean_score_time': array([0.00303836, 0.00361395, 0.00302796, 0.00332041]),
 'std_score_time': array([2.46342586e-05, 6.18079187e-05, 7.91219849e-05, 8.48670214e-05]),
 'param_C': masked_array(data=[1, 1, 10, 10],
              mask=[False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['linear', 'rbf', 'linear', 'rbf'],
              mask=[False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'linear'},
  {'C': 1, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'}],
 'split0_test_score': array([0.99115624, 0.95447101, 0.9901736 , 0.96364232]),
 'split1_test_score': array([0.99312152, 0.97772683, 0.99115624, 0.98788077]),
 'split2_test_score': array([0.99801587, 0.98148148, 0

In [40]:
import scipy.stats

## w liscie parametrow do testowania musimy powiedziec z jakim rozkladem wartosci powinny byc losowane
parameters_distribution = {'C': scipy.stats.uniform(0,1), 
                           'gamma': scipy.stats.expon(scale=.1),
  'kernel': ['rbf', 'linear'], 'class_weight':['balanced', None]}

clf_random = RandomizedSearchCV(svc, parameters_distribution, random_state=0)
clf_random.fit(cancer_X, cancer_y)

RandomizedSearchCV(estimator=SVC(),
                   param_distributions={'C': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7f47998d7220>,
                                        'class_weight': ['balanced', None],
                                        'gamma': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7f47998dc160>,
                                        'kernel': ['rbf', 'linear']},
                   random_state=0)

In [41]:
clf_random.cv_results_['params']

[{'C': 0.5488135039273248,
  'class_weight': None,
  'gamma': 0.18596042409118513,
  'kernel': 'linear'},
 {'C': 0.5448831829968969,
  'class_weight': None,
  'gamma': 0.09770064274254157,
  'kernel': 'rbf'},
 {'C': 0.4375872112626925,
  'class_weight': 'balanced',
  'gamma': 0.005838467078070335,
  'kernel': 'rbf'},
 {'C': 0.3834415188257777,
  'class_weight': 'balanced',
  'gamma': 0.16722112126272706,
  'kernel': 'rbf'},
 {'C': 0.5680445610939323,
  'class_weight': None,
  'gamma': 0.18083692319941533,
  'kernel': 'rbf'},
 {'C': 0.08712929970154071,
  'class_weight': None,
  'gamma': 0.04592481411779334,
  'kernel': 'linear'},
 {'C': 0.7781567509498505,
  'class_weight': None,
  'gamma': 0.2040892272036123,
  'kernel': 'linear'},
 {'C': 0.7991585642167236,
  'class_weight': None,
  'gamma': 0.07349644192364166,
  'kernel': 'linear'},
 {'C': 0.11827442586893322,
  'class_weight': 'balanced',
  'gamma': 0.08723211970403807,
  'kernel': 'linear'},
 {'C': 0.9446689170495839,
  'class_we

## 3. Optymalizacja Bayesowska

<img src="image/BO.gif" width="750" align="center">

In [86]:
# !pip install scikit-optimize

In [85]:
import scipy, skopt

In [88]:
?RandomForestClassifier


In [97]:
## zdefiniowanie przedstrzeni przeszukiwań

search_spaces = {
        'criterion': ['gini', 'entropy'],
        'n_estimators': skopt.space.space.Integer(1, 500),
        'max_depth': skopt.space.space.Integer(2, 10)
}



In [98]:

rf = RandomForestClassifier()
opt_1 = skopt.BayesSearchCV(
        estimator=rf,
        search_spaces=search_spaces,
        scoring='roc_auc',
        n_jobs=4,
        n_iter=10,
        verbose=0,
        random_state=1
    )
opt_1.fit(cancer_X, cancer_y)

BayesSearchCV(estimator=RandomForestClassifier(), n_iter=10, n_jobs=4,
              random_state=1, scoring='roc_auc',
              search_spaces={'criterion': ['gini', 'entropy'],
                             'max_depth': Integer(low=2, high=10, prior='uniform', transform='normalize'),
                             'n_estimators': Integer(low=1, high=500, prior='uniform', transform='normalize')})

# Praca domowa 2 - termin oddania kolejna środa, do końca dnia

Dla zbioru danych opracowanego w poprzedniej pracy domowej dopasować wybrany model uczenia maszynowego i go zwdalidować (AUC i jedna inna wybrana metryka) dla domyślnych hiperparametrów. 
W kolejnym kroku należy przeprowadzić optymalizację hiperparametrów metodami:
1. ręczna zmiana hiperparametrów
2. random search
3. grid search
4. optymalizacja bayesowska

Jeśli dla opracowanego zbioru danych wybrany algorytm ML nie działa, należy odpowiednio zmodyfikować zbiór danych.

Rozwiązanie należy przygotować w formie raportu (kod z komentarzami) w formacie `ipnyb` lub `.html` i umieścić w foldarze `homeworks/hw2/NazwiskoImie`.

